{
 "title": "Enclave Logs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1>Enclave Logs</h1>\n<p align=\"center\">\n    <img src=\"https://github.com/EnclaveRunner/.github/raw/main/img/enclave-logo.png\" alt=\"Description of image\" width=\"200\"/>\n</p>\n"
   }
  },
  {
   "title": "Infos",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({app=\"docker\"} |~ `(?i)info` or `(?i)inf` [$__auto]))"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({app=\"docker\"} |~ `(?i)warn` or `(?i)warning` [$__auto]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({app=\"docker\"} |~ `(?i)error` or `(?i)err` [$__auto]))"
    }
   ]
  },
  {
   "title": "Cadvisor Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"cadvisor\"} |= ``",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "Loki Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"loki\"} |= ``",
     "maxLines": 100
    }
   ]
  }
 ]
}